### ISSUE TITLE
[Settings] The Sign Out "Flyout" is Fluent styled instead of following the selected theme

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/uno.todo#165] opened 2022-04-29 15:16 UTC
## Current behavior

On sign out the user is presented with Fluent styled component instead of Material or selected Theme

## Expected behavior

All app components should follow the same theme

## How to reproduce it (as minimally and precisely as possible)

Sign out from app and Observe

## Environment

Mac
OS Chrome Version 100.0.4896.75 (Official Build) (x86_64) 
Private window
__
Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Same issue in the Delete for the Delete Flyout in Home page

**Comment by agneszitte-nventive** [comment] 2022-05-10 16:26
Closing this issue as it's a duplicate of https://github.com/unoplatform/uno.todo/issues/253

**Closed by agneszitte-nventive** 2022-05-10 16:26 UTC
Labels: kind/bug, triage/untriaged
